config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :dashboards, only: :index

  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      get :education_details
      get :professional_details
    end
  end

  namespace :end_users do
    resources :users, only: [:edit, :show, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  PASSWORD_FORMAT = /\A
    (?=.{8,})
    (?=.*[A-Z])
    (?=.*\W)
  /x

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password,
    presence: true,
    length: { in: (7..60) },
    format: { with: PASSWORD_FORMAT },
    confirmation: true,
    on: :create

  has_many :education_details, dependent: :destroy
  has_many :professional_details, dependent: :destroy
  has_one :personal_detail, dependent: :destroy
  belongs_to :role

  scope :end_users, -> { where(role_id: Role.find_by(name: 'EndUser').id) }

  delegate :name, to: :role, prefix: true, allow_nil: true

  accepts_nested_attributes_for :education_details, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :professional_details, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :personal_detail, reject_if: :all_blank, allow_destroy: true

  validate :max_education_details, :max_professional_details

  def is_admin?
    role_name == 'Admin'
  end

  def is_end_user?
    role_name == 'EndUser'
  end

  def max_education_details
    if education_details.size > 5
      self.errors.add(:base, "Total Education Details cannot be greater than 5")
    end
  end

  def max_professional_details
    if professional_details.size > 10
      self.errors.add(:base, "Total Professional Details cannot be greater than 10")
    end
  end


  class << self

    def advance_search(search_params)
      users = all
      if search_params[:degree].present?
        users = users.references(:education_details).where("education_details.degree=?", "#{search_params[:degree]}")
      end
      if search_params[:college_name].present?
        users = users.references(:education_details).where("education_details.college_name=?", "#{search_params[:college_name]}")
      end
      users
    end

  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  before_action :find_user, only: [:education_details, :professional_details, :show]

  PER_PAGE = 25

  def index
    @users = User.includes(
      :role,
      :education_details,
      :personal_detail,
      :professional_details,
    ).end_users
    if params[:is_advanced_search].present?
      @users = @users.advance_search(advance_search_params)
    end
    respond_to do |format|
      format.html do
        @users = @users.paginate(page: params[:page], per_page: PER_PAGE)
      end
    end
  end

  def show
  end

  def education_details
    @education_details = @user.education_details
    render_modal('education_details')
  end

  def professional_details
    @education_details = @user.professional_details
    render_modal('professional_details')
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      flash[:notice] = 'User Deleted Successfully!!'
      redirect_to admin_users_path
    else
      flash[:notice] = 'User Deletion Failed!!'
      redirect_to admin_users_path
    end
  end

  private

  def find_user
    @user = User.includes(:professional_details, :role, :education_details).end_users.find_by(id: params[:user_id])
  end

  def advance_search_params
    params.permit(
      [
        :college_name,
        :degree
      ]
    )
  end

end

app/controllers/concerns/users.rb
module Users
  extend ActiveSupport::Concern

  included do

    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password,
        personal_detail_attributes: [
          :contact_no,
          :address,
          :id,
        ],
        education_details_attributes: [
          :college_name,
          :degree,
          :_destroy,
          :id
        ],
        professional_details_attributes:[
          :prev_employer,
          :position,
          :_destroy,
          :id
        ]
      )
    end

  end
end

app/controllers/end_user_controller.rb
class EndUserController < ApplicationController

  before_action :authenticate_user!, :authorized_end_user!

  def authorized_end_user!
    unless current_user.is_end_user?
      flash[:error] = 'You are not authorized to access this page'
      respond_to do |format|
        format.html do
          redirect_to '/'
        end
      end
    end
  end


end

app/controllers/end_users/users_controller.rb
module EndUsers

  class UsersController < EndUserController

    include ::Users

    before_action :find_user

    def edit
      render 'users/edit'
    end

    def update
      if @user.update(user_params)
        flash[:notice] = 'Details Updated Successfully'
        redirect_to end_users_user_path(@user)
      else
        render 'users/edit'
      end
    end

    private

    def find_user
      @user = current_user
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include Users

  def new
    @user = User.new
    @user.build_personal_detail
    @user.education_details.build
    @user.professional_details.build
  end

  def create
    @role = Role.end_user
    @user = @role.users.new(user_params)
    if @user.save
      flash[:notice] = 'Your Account Is Created Successfully'
      redirect_to new_user_session_path
    else
      render 'new'
    end
  end


end

app/helpers/end_user_helper.rb
module EndUserHelper
end

app/helpers/end_users/users_controller_helper.rb
module EndUsers::UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/end_users/users/_education_details_fields.html.erb
<div class="nested-fields info-container" style="border: 1px dashed #999; border-radius: 5px; padding: 20px; width: 49%; display: inline-block; margin: 2px 0;">
  <div class="form-group">
    <%= f.text_field :college_name, class: "form-control", required: true %>
    <%= f.text_field :degree, class: "form-control", required: true %>
  </div>
  <br/>
  <center>
    <%= link_to_remove_association fa_icon("trash-o"), f, :class=>"btn btn-danger" %>
  </center>
</div>

app/views/end_users/users/_professional_details_fields.html.erb
<div class="nested-fields info-container" style="border: 1px dashed #999; border-radius: 5px; padding: 20px; width: 49%; display: inline-block; margin: 2px 0;">
  <div class="form-group">
    <%= f.text_field :prev_employer, class: "form-control", label: 'Previous Employer', required: true %>
    <%= f.text_field :position, class: "form-control", label: 'Designation',required: true %>
  </div>
  <br/>
  <center>
    <%= link_to_remove_association fa_icon("trash-o"), f, :class=>"btn btn-danger" %>
  </center>
</div>

app/views/end_users/users/show.html.erb
<div class="col-md-6">
  <div class="holder-form-modal" style="margin-top: 66px;">
    <div class="modal-header booking-modal-header">
      <h5 class="modal-titlePayment" id="exampleModalLabel">My Profile</h5>
    </div>
    <div class="modal-body pb-0 pt-0">
      <div class="wrapper center-block">
        <div class="form-heading">
          <div class="row">
            <div class="col-md-4">
              Profile Details
            </div>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-md-12">
            <h3></h3>
          </div>
          <div class="form-group col-md-6">
            <label>
              UserName:
            </label>
            <span class="d-block mt-1"><%= @user.username %></span>
          </div>
          <div class="form-group col-md-6">
            <label>
              Email:
            </label>
            <span class="d-block mt-1"><%= @user.email %></span>
          </div>
        </div>
        <div class="form-heading">
          <div class="row">
            <div class="col-md-4">
              Personal Details
            </div>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-md-12">
            <h3></h3>
          </div>
          <div class="form-group col-md-6">
            <label>
              Contact No:
            </label>
            <span class="d-block mt-1"><%= @user.personal_detail&.contact_no %></span>
          </div>
          <div class="form-group col-md-6">
            <label>
              Address:
            </label>
            <span class="d-block mt-1"><%= @user.personal_detail&.address %></span>
          </div>
        </div>
        <div class="form-heading">
          <div class="row">
            <div class="col-md-4">
              Education Details
            </div>
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-bordered table-hover table-sm responsive nowrap" style="width:100%!important">
                      <thead>
                        <tr>
                          <th class="all">UserName</th>
                          <th class="all">CollegeName</th>
                          <th class="desktop">Degree</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @user.education_details.each do |ed| %>
                          <tr>
                            <td>
                              <%= ed.user.username %>
                            </td>
                            <td>
                              <%= ed.college_name %>
                            </td>
                            <td>
                              <%= ed.degree %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="form-heading">
          <div class="row">
            <div class="col-md-4">
              Professional Details
            </div>
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-bordered table-hover table-sm responsive nowrap" style="width:100%!important">
                      <thead>
                        <tr>
                          <th class="all">UserName</th>
                          <th class="all">Previous Employer</th>
                          <th class="desktop">Designation</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @user.professional_details.each do |pd| %>
                          <tr>
                            <td>
                              <%= pd.user.username %>
                            </td>
                            <td>
                              <%= pd.prev_employer %>
                            </td>
                            <td>
                              <%= pd.position %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="form-heading" style="margin-top=10px">
          <div class="row">
            <div class="col-md-4">
              <%= link_to 'Edit', edit_end_users_user_path(@user), class: 'btn btn-lg btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>
<br/>