config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :dashboards, only: :index

  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      get :education_details
      get :professional_details
    end
  end

  namespace :end_users do
    resources :users, only: [:edit, :show, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  PASSWORD_FORMAT = /\A
    (?=.{8,})
    (?=.*[A-Z])
    (?=.*\W)
  /x

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password,
    presence: true,
    length: { in: (7..60) },
    format: { with: PASSWORD_FORMAT },
    confirmation: true,
    on: :create

  has_many :education_details, dependent: :destroy
  has_many :professional_details, dependent: :destroy
  has_one :personal_detail, dependent: :destroy
  belongs_to :role

  scope :end_users, -> { where(role_id: Role.find_by(name: 'EndUser').id) }

  delegate :name, to: :role, prefix: true, allow_nil: true

  accepts_nested_attributes_for :education_details, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :professional_details, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :personal_detail, reject_if: :all_blank, allow_destroy: true

  validate :max_education_details, :max_professional_details

  def is_admin?
    role_name == 'Admin'
  end

  def is_end_user?
    role_name == 'EndUser'
  end

  def max_education_details
    if education_details.size > 5
      self.errors.add(:base, "Total Education Details cannot be greater than 5")
    end
  end

  def max_professional_details
    if professional_details.size > 10
      self.errors.add(:base, "Total Professional Details cannot be greater than 10")
    end
  end


  class << self

    def advance_search(search_params)
      users = all
      if search_params[:degree].present?
        users = users.references(:education_details).where("education_details.degree=?", "#{search_params[:degree]}")
      end
      if search_params[:college_name].present?
        users = users.references(:education_details).where("education_details.college_name=?", "#{search_params[:college_name]}")
      end
      users
    end

  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  before_action :find_user, only: [:education_details, :professional_details, :show]

  PER_PAGE = 25

  def index
    @users = User.includes(
      :role,
      :education_details,
      :personal_detail,
      :professional_details,
    ).end_users
    if params[:is_advanced_search].present?
      @users = @users.advance_search(advance_search_params)
    end
    respond_to do |format|
      format.html do
        @users = @users.paginate(page: params[:page], per_page: PER_PAGE)
      end
    end
  end

  def show
  end

  def education_details
    @education_details = @user.education_details
    render_modal('education_details')
  end

  def professional_details
    @education_details = @user.professional_details
    render_modal('professional_details')
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      flash[:notice] = 'User Deleted Successfully!!'
      redirect_to admin_users_path
    else
      flash[:notice] = 'User Deletion Failed!!'
      redirect_to admin_users_path
    end
  end

  private

  def find_user
    @user = User.includes(:professional_details, :role, :education_details).end_users.find_by(id: params[:user_id])
  end

  def advance_search_params
    params.permit(
      [
        :college_name,
        :degree
      ]
    )
  end

end

app/controllers/concerns/users.rb
module Users
  extend ActiveSupport::Concern

  included do

    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password,
        personal_detail_attributes: [
          :contact_no,
          :address,
          :id,
        ],
        education_details_attributes: [
          :college_name,
          :degree,
          :_destroy,
          :id
        ],
        professional_details_attributes:[
          :prev_employer,
          :position,
          :_destroy,
          :id
        ]
      )
    end

  end
end

app/controllers/end_users/users_controller.rb
module EndUsers

  class UsersController < EndUserController

    include ::Users

    before_action :find_user

    def edit
      render 'users/edit'
    end

    def update
      if @user.update(user_params)
        flash[:notice] = 'Details Updated Successfully'
        redirect_to end_users_user_path(@user)
      else
        render 'users/edit'
      end
    end

    private

    def find_user
      @user = current_user
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include Users

  def new
    @user = User.new
    @user.build_personal_detail
    @user.education_details.build
    @user.professional_details.build
  end

  def create
    @role = Role.end_user
    @user = @role.users.new(user_params)
    if @user.save
      flash[:notice] = 'Your Account Is Created Successfully'
      redirect_to new_user_session_path
    else
      render 'new'
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_advance_search_form.erb
<div class="box-body" id="adv-searchbox">
  <%= form_tag nil, method: :get, class: "filter-search-menu" do %>
    <div class="row">
      <%= hidden_field_tag :is_advanced_search, true %>
      <div class="col-xs-6 col-md-3">
        <div class="form-group">
          <%= select_tag "college_name", options_for_select(fetch_all_college_name, params[:college_name]), prompt: 'Please Select College Name ', class: "form-control multiselect" %>
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="form-group">
          <%= select_tag "degree_name", options_for_select(fetch_all_degree_name, params[:college_name]), prompt: 'Please Select Degree Name', class: "form-control multiselect" %>
        </div>
      </div>
      <div class="col-xs-6 col-md-2">
        <div class="form-group">
          <%= button_tag type: "submit", class: "btn btn-primary btn-flatbtn btn-sm" do %>
            <%= fa_icon "search" %>
            Search
          <% end %>
          <%= link_to nil, class: "btn btn-default btn-sm pd-fixes" do %>
            <%= fa_icon "refresh" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/_education_details.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalCenterTitle">Education Detail</h5>
  <button aria-label="Close" class="close" data-dismiss="modal" type="button"></button>
  <span aria-hidden="true">×</span>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-sm responsive nowrap" style="width:100%!important">
              <thead>
                <tr>
                  <th class="all">UserName</th>
                  <th class="all">CollegeName</th>
                  <th class="desktop">Degree</th>
                </tr>
              </thead>
              <tbody>
                <% @education_details.each do |ed| %>
                  <tr>
                    <td>
                      <%= ed.user.username %>
                    </td>
                    <td>
                      <%= ed.college_name %>
                    </td>
                    <td>
                      <%= ed.degree %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/admin/users/_professional_details.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalCenterTitle">Professional Detail</h5>
  <button aria-label="Close" class="close" data-dismiss="modal" type="button"></button>
  <span aria-hidden="true">×</span>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-sm responsive nowrap" style="width:100%!important">
              <thead>
                <tr>
                  <th class="all">UserName</th>
                  <th class="all">Previous Employer</th>
                  <th class="desktop">Designation</th>
                </tr>
              </thead>
              <tbody>
                <% @education_details.each do |ed| %>
                  <tr>
                    <td>
                      <%= ed.user.username %>
                    </td>
                    <td>
                      <%= ed.prev_employer %>
                    </td>
                    <td>
                      <%= ed.position %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/admin/users/index.html.erb
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-md-9">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/">Home</a>
            </li>
            <li class="breadcrumb-item active">Users</li>
          </ol>
          <center>
            <h1 class="m-0 text-dark">Users</h1>
          </center>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <div class="box-header row">
          <div class="pull-left col-md-6 mb-2">
            <div class="input-group input-group-sm">
              <div class="input-group-btn">
                <a class="btn btn-primary btn-sm" href="javascript:void(0);" id="adv-search" style="margin-left:-2px;">
                  Advanced Search
                  <i class="fa fa-angle-down"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
        <%= render partial: "advance_search_form" %>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered table-hover dataTables table-sm responsive nowrap" style="width:100%!important">
                <thead>
                  <tr>
                    <th class="all">UserName</th>
                    <th class="all">Email</th>
                    <th class="desktop">Contact</th>
                    <th class="all">Address</th>
                    <th class="desktop">EducationDetails</th>
                    <th class="desktop">Work Experience</th>
                    <th class="desktop">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                    <tr>
                      <td>
                        <%= user.username %>
                      </td>
                      <td>
                        <%= user.email %>
                      </td>
                      <td>
                        <%= user.personal_detail&.contact_no %>
                      </td>
                      <td>
                        <%= user.personal_detail&.address %>
                      </td>
                      <td>
                        <%= link_to (fa_icon "eye"), admin_user_education_details_path(user), remote: true, class: "btn btn-primary btn-sm" %>
                      </td>
                      <td>
                        <%= link_to (fa_icon "eye"), admin_user_professional_details_path(user), remote: true, class: "btn btn-primary btn-sm" %>
                      </td>
                      <td>
                        <%= link_to (fa_icon "trash"), admin_user_path(user), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: 'Are You Sure want to Delete this User'} %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <% if @users.present? %>
            <div class="pagination-custom-holder">
              <strong style="margin-left: 0;"><%= "Users Count - #{@users.total_entries}"%></strong>
              <%= will_paginate @users, :class  =>  "ct-pag" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>